### ISSUE TITLE
Incorrect post-length counting

### ISSUE THREAD

**Issue by ratkins** [videah/SkyBridge#10]
I just tried to respond to a post from Ivory (on the iPad) and it errored out with a “the server is having difficulties right now” toast message. Ivory’s UI didn’t indicate the message was too long but I suspected that was the problem and split it in two and each post (under 300 chars) posted fine.

It seems Skybridge isn’t correctly communicating to Ivory that the Skybridge instance’s character limit is only 300?

**Comment by videah** [comment]
This is an issue on Ivory's end, [SkyBridge reports that the character limit is 300](https://github.com/videah/SkyBridge/blob/9ada9ae8db05a22b7328ebc25f87e6f3fca36fc2/routes/api/v1/instance.dart#L40) but Ivory doesn't do anything with it yet. Other Mastodon clients like Mona correctly recognise the max char limit.

https://tapbots.social/@ivory/109807867106510953

<img width="576" alt="image" src="https://github.com/videah/SkyBridge/assets/4761786/99168c44-ab46-4095-8c89-fc5e9aea44ac">

**Comment by ratkins** [comment]
Aha, sorry to bother you.
