### ISSUE TITLE
Exception when loading timeline

### ISSUE THREAD

**Issue by felixmueller** [videah/SkyBridge#16]
Hi @videah 

my local docker installation was working smoothly until now:

![image](https://github.com/videah/SkyBridge/assets/115331/64598b12-69c9-4f30-bc7e-43964abd5290)

I already pulled the latest build but without success.

Can you look into this error message?

Thank you very much!

**Comment by videah** [comment]
This is a result of a change on Bluesky's end that will require the [upstream Dart library](https://github.com/myConsciousness/atproto.dart/tree/main/packages/bluesky) to make changes to fix, I've let the author know so hopefully it will be fixed soon! Sorry for the trouble 😢

**Comment by videah** [comment]
Should be fixed in b951511d7fcbea6f800b6c4d009d7bd3764f55fa
