### ISSUE TITLE
Show custom Bluesky feeds as lists

### ISSUE THREAD

**Issue by cbirdsong** [videah/SkyBridge#17]
Bluesky has added a custom feed system: https://www.theverge.com/2023/5/26/23739174/bluesky-custom-feeds-algorithms-twitter-alternative

It would neat if these could be surfaced on Skybridge as different lists.

**Comment by videah** [comment]
This is already partially implemented! Creating a list with the name set to the handle running the feed will let you use one of the feeds, there needs to be more done to make this work better (there's no way to pick what feed if the account runs multiple)

**Comment by videah** [comment]
With 355f8b7 Feeds are now loaded as lists directly from the users preferences, no input by the user required! At the moment this requires feeds to be subscribed to in the official app but I think this is more usable for now
