### ISSUE TITLE
Text cuts off after certain symbols

### ISSUE THREAD

**Issue by wesley-maney** [videah/SkyBridge#19]
I don't know if it's because of Ivory or if it's a SkyBridge issue - but I have tested this on my Mastodon account in Ivory as well and the issue does not appear there.

When creating a post with a "<" in it (specifically I have tested this with: "<3"), SkyBridge cuts off the text at that character.

So a post with the text:
"This is a test <3 and then some more words"
will show in Ivory as:
"This is a test "

Images still work and I have not tested it with other special characters.

<img width="599" alt="Screenshot 2023-06-23 at 00 49 09" src="https://github.com/videah/SkyBridge/assets/13488705/53ee8f76-9614-4185-bb6a-d1e5caaaf343">

The correct post on Bluesky.

<img width="399" alt="Screenshot 2023-06-23 at 00 49 03" src="https://github.com/videah/SkyBridge/assets/13488705/6a3c274b-547b-46f7-bd28-49e022abd9e7">

The cut off post on Ivory/SkyBridge.

(And thanks again for creating this project!)

**Comment by videah** [comment]
Thank you for the report, glad you're getting some use out of the project! This should be fixed by 464814a
