### ISSUE TITLE
Feature Request: Support Long Press To Boost/Fav From Other Accounts

### ISSUE THREAD

**Issue by mergesort** [videah/SkyBridge#20]
Hi @videah, like I've mentioned elsewhere I'm absolutely loving SkyBridge, it's helped me be a lot more active on Bluesky in lieu of a good native client. I did have a request though, it may not be possible but I was wondering if it's possible to add functionality for boosting/favoriting from other logged in accounts like this?

![Favorite From Other Account](https://github.com/videah/SkyBridge/assets/716513/305c0d66-f912-4fa9-8296-12ad7d0a132f)

My goal is to boost posts from an alt account, one where I like to curate a collection of good posts. The way Ivory accomplishes this on Mastodon is by long-pressing on the boost or star icons. I was wondering if it's possible to similarly route the Bluesky boost/fav request to another logged in Bluesky account when a user long-presses and chooses a different Bluesky account [logged in on Ivory through SkyBridge].

Thank you so much!

**Comment by videah** [comment]
Sorry for the wait, should now be implemented as of 67ecba910202e9f03ebfcfc049088cc04b32fb6d!

**Comment by mergesort** [comment]
Oh wow, thank you so much @videah!
