### ISSUE TITLE
Feature Request: Delete Post

### ISSUE THREAD

**Issue by mergesort** [videah/SkyBridge#21]
Hi there again, I realized I had one more feature request to ask about. 😅  

I'm not sure if it's technically difficult but I was wondering if it'd be possible to support deleting Bluesky posts from inside Ivory in the future? It's one of the few things I still open the native app for, when I compose a typo and don't notice.

Thank you so much!

**Comment by videah** [comment]
Should be implemented!

**Comment by mergesort** [comment]
As always thank you so much @videah!
