### ISSUE TITLE
Can't access Bluesky using Metatext

### ISSUE THREAD

**Issue by malagem** [videah/SkyBridge#23]
When trying to access Bluesky through the Metatext mastodon client, an error is thrown after the login screen, stating "The data couldn't be read because it is missing". It looks like the registration steps has succeeded but the client is unable to pull any data from Bluesky through the Skybridge connector.

**Comment by videah** [comment]
Can now confirm that Metatext now renders feeds and profile properly
![IMG_8409](https://github.com/videah/SkyBridge/assets/4761786/13bbaa62-debb-4de5-b818-e0ee69f694bb)
