### ISSUE TITLE
Show some meaningful contents at /@id/1234

### ISSUE THREAD

**Issue by xnuk** [videah/SkyBridge#29]
Currently shows only "route not found". Some mastodon client does not use link preview cards at all, so I cannot view or guess some of quoted posts.

Possible contents:
- Show the post content, even plain text only is just okay.
- Redirect to bsky.app or view-only services like blue.amazingca.dev
- Implement application/activity+json

**Comment by videah** [comment]
Implemented in 0342226, just redirecting to bsky.app for now.
