### ISSUE TITLE
Duplicate posts in home timeline

### ISSUE THREAD

**Issue by MikeASchneider** [videah/SkyBridge#30]
As of yesterday evening, I have been seeing a lot of duplicate posts in my home timeline in Ivory (iOS and Mac). Sometimes it is one post several times in a row, sometimes it is a small group of two to four posts that repeat in sequence several times in a row.

<img width="411" alt="A post from Rob Zacny about single-take sequences in film repeated five times in a row on my timeline" src="https://github.com/videah/SkyBridge/assets/934698/d2197f8e-6a9e-4eea-b543-fb31608ef289">

**Comment by karimlevallois** [comment]
I had a couple of hours of this too, but seems to have sorted itself out for some reason.

**Comment by MysteryPollster** [comment]
Seeing same in Ivory on iPad in the past hour, though also saw similar earlier today. Seems to occur more often when I pull-to-refresh. 

<img width="820" alt="New Note" src="https://github.com/videah/SkyBridge/assets/35932128/02f324a8-8e0e-435f-b996-7014201be1a0">

**Comment by MysticalOS** [comment]
Seeing a lot of this too. comes and goes. but is def more prominent last day or so

**Comment by videah** [comment]
Not sure how to replicate this but looking into it soon

**Comment by videah** [comment]
Ok it might have been a simple fix, let me know if you see any more duplicates after the change in cbf3775

**Comment by MikeASchneider** [comment]
@videah I haven't seen duplicates since you sent this comment. However, I think this fix has brought back #11 which seemed to be fixed while I was seeing the duplicate post bug.

**Comment by MysteryPollster** [comment]
Same experience as @MikeASchneider: No duplicates since your comment, but also seeing #11 again (though I still see unread counts in Ivory for Mac, not in Ivory for iOS)

**Comment by videah** [comment]
No reports of duplicates in a while, closing this for now
