### ISSUE TITLE
Images not shown in quote posts

### ISSUE THREAD

**Issue by felixmueller** [videah/SkyBridge#33]
I just experienced a problem with quote posts containing images:

Ivory via SkyBridge:
![image](https://github.com/videah/SkyBridge/assets/115331/96f231f7-9ee9-4e42-b4e5-2a3c7d86d2de)

Bluesky:
![image](https://github.com/videah/SkyBridge/assets/115331/bd1e46a2-1a51-431a-bc91-e4b1e1d20d1a)

Thank you very much for looking into this! 🙏

**Comment by videah** [comment]
Unfortunately this is a side effect of how we're abusing embed cards to handle quote posts, Ivory will either display a card or display an image, but not both 😔 I'm not sure how to go about fixing this other than maybe not showing a card when there's an image and just showing a link instead

**Comment by mergesort** [comment]
I think not showing the card and showing the link instead is a great solution, preferred even since it's Ivory's default behavior.

**Comment by felixmueller** [comment]
I would go for a link instead of the card for cases where posts contain images as well. 
Of course it's not as nice but loosing the whole images without even knowing is not an option in my opinion. 
Thanks a lot in advance for implementing this! 👌

**Comment by chkuendig** [comment]
I just noticed this as well. Image + link would be the besser solution for sure.

**Comment by videah** [comment]
Fixed as of 94370ec, quote posts will render like this when an image is attached, tapping the link will bring you to the original post

![IMG_2460](https://github.com/videah/SkyBridge/assets/4761786/d9e3054c-5092-4512-b27e-e8b0bcc73cb3)
