### ISSUE TITLE
Can’t post images 

### ISSUE THREAD

**Issue by millionsofplayers** [videah/SkyBridge#40]
I can add alt text and everything, but when I try to post an image it only posts the text

**Comment by videah** [comment]
What client are you using? Do you know how big the file is?

**Comment by MysticalOS** [comment]
I pretty much gave up on that a while back. I couldn't get even small images to work using ivory. Been using official app to do that.

**Comment by videah** [comment]
Should be fixed by 004bffe, still need to do work to compress images when need be.
