### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by sevencookies** [videah/SkyBridge#46]
![IMG_0002](https://github.com/videah/SkyBridge/assets/66103847/43a28bc3-fe8d-4d18-b134-183e1ea6e369)

A permission denied message appears after adding and logging in a skybridge.fly.dev user to Ivory.

**Comment by videah** [comment]
Sorr about that, this was a deployment issue on my end and it should hopefully be working now!

**Comment by sevencookies** [comment]
Yes, thank you. Issue resolved
