### ISSUE TITLE
Typing quotes in a posts text body causes post to say it failed (when it didn't)

### ISSUE THREAD

**Issue by MysticalOS** [videah/SkyBridge#47]
![Screenshot 2023-09-01 at 6 48 23 PM](https://github.com/videah/SkyBridge/assets/1899149/0ebecc05-ac23-4b6c-9f08-f30385b23a6d)
first two said it failed, but 3rd said it succeeded (whenI changed " to ')

but all 3 actually sent.

**Comment by videah** [comment]
I can't seem to replicate this as of the latest build, if anyone still encounters this please let me know.
