### ISSUE TITLE
"Hashtags" not displayed in Ivory

### ISSUE THREAD

**Issue by felixmueller** [videah/SkyBridge#55]
Hi @videah,
Posts containing "hash tags" (I know they don't exist in Bluesky) are displayed in Ivory without the tags at all.
Is there any possibility to render the tags (stripping out the # character would be ok I guess)?
Thanks a lot!
![image](https://github.com/videah/SkyBridge/assets/115331/beddcc4e-14a6-482c-b793-712a07376166)
![image](https://github.com/videah/SkyBridge/assets/115331/d5121b01-568d-4734-82ed-22de42013571)

**Comment by videah** [comment]
Should be fixed as of ee00d6c!
