### ISSUE TITLE
Failed authorization from “skybridge.fly.dev”

### ISSUE THREAD

**Issue by xtraa** [videah/SkyBridge#56]
probably normal, but IDK how to go on from here, after following the website instructions. 

Tried with Ivory and Mastonaut. Where do I have to ask for authorization?
bsky pw generated, all fine. just refuses to take my handle.

**Comment by videah** [comment]
There are sometimes issues with using your handle to sign in, have you tried using your email?

**Comment by tom111** [comment]
I also tried the first time today and could not get it to work (in either client). This is with e-mail in Ivory, but other methods and clients are similar
<img width="421" alt="image" src="https://github.com/videah/SkyBridge/assets/123542/4ca35a46-ab65-41bd-87b3-82dbd9b6696d">

**Comment by tom111** [comment]
I had not confirmed my e-mail for that account. Try confirming it and log in with e-mail then.
