### ISSUE TITLE
Docker Container broken?

### ISSUE THREAD

**Issue by revunix** [videah/SkyBridge#59]
Hello, I have tried several times now to start my own server. Unfortunately, it always fails with this error:

I wanted to create the container with `docker build .`

![CleanShot 2023-10-24 at 14 12 15](https://github.com/videah/SkyBridge/assets/4172418/224f8681-f090-4486-a4d1-cdccf83ea11f)

**Comment by marcelinollano** [comment]
I've got it running by using `dart_frog` version `0.3.8`, both in the CLI and as a package. It seems like this issue is also affecting version `1.0.0`.

**Comment by revunix** [comment]
@marcelinollano How did you install the 0.3.8?

**Comment by marcelinollano** [comment]
I modified the `Dockerfile` to include the version:

```
RUN dart pub global activate dart_frog_cli 0.3.8
```
and `pubspec.yaml`

```
dart_frog: 0.3.8
```

after that I also had to update `pubspec.lock` with `dart pub get`, I think.

**Comment by videah** [comment]
As of c58a45c I've downgraded dart_frog for now until I have enough time to figure out a real fix
