### ISSUE TITLE
Can't access SkyBridge in Mammoth

### ISSUE THREAD

**Issue by LauraLangdon** [videah/SkyBridge#6]
After entering credentials to log in to SkyBridge using Mammoth, I get this error screen:
![image](https://github.com/videah/SkyBridge/assets/48335772/8c691570-4a91-432a-bdc9-9f5477e1db7a)

**Comment by hellstabber** [comment]
I have the same problem

**Comment by 0wg** [comment]
same issue here

**Comment by videah** [comment]
After ac47bf9 and e5eb7c0 Mammoth now renders bluesky feeds and profiles.

![IMG_8410](https://github.com/videah/SkyBridge/assets/4761786/d6efef30-e61d-4994-b5d7-feefc767eb9a)
