### ISSUE TITLE
Rate limit exceeded

### ISSUE THREAD

**Issue by Tkalland** [videah/SkyBridge#61]
Error Message “Mastodon: rate limit exceeded” appears after just a few refreshes of the timeline. 

The same happens in Ivory, Mona and Phanby.

**Comment by videah** [comment]
This is unfortunately a limitation on Bluesky's end. The public instance is served from a single IPv4 and all Bluesky rate limits are per-IP and not per-user. As more people use the public instance the more likely it is to hit their rate limits. This will hopefully change in the future as Bluesky build out their tooling but as of right now they have no way to increase our limits. In the meantime you can selfhost to get past these limitations, I will be writing documentation on this soon.

**Comment by Tkalland** [comment]
That makes sense, thanks!

**Comment by codebykat** [comment]
@videah In light of the news that Bluesky posts are now public, I wonder if there's a hack/workaround now? Would it be possible to e.g. request public post data unauthenticated and only use authenticated calls for actions like boost/favorite? The rate limit message really makes it hard to use Skybridge/bsky, sadly. It feels like I see it every third time I try to do anything.

**Comment by videah** [comment]
> @videah In light of the news that Bluesky posts are now public, I wonder if there's a hack/workaround now? Would it be possible to e.g. request public post data unauthenticated and only use authenticated calls for actions like boost/favorite? The rate limit message really makes it hard to use Skybridge/bsky, sadly. It feels like I see it every third time I try to do anything.

The rate limit is based on number of requests per-IP rather than per account, even when unauthenticated it would still hit the limit unfortunately. The only way around the issue is self-hosting which I *really* need to write some documentation about soon.
