### ISSUE TITLE
Error when accessing self hosted SkyBridge docker instance

### ISSUE THREAD

**Issue by felixmueller** [videah/SkyBridge#7]
Hi @videah,

first of all: thanks a lot for providing this awesome tool!

Today I tried to pull the latest docker image "videah/skybridge:latest" and it seems to start.

I get the following messages in the log:
```
Starting skybridge ... done
Attaching to skybridge
skybridge    | Wiping ID database...
skybridge    | ✓ Running on http://:::8080
skybridge    | 2023-05-20T10:33:06.580077  0:00:00.000196 GET     [404] /favicon.ico
skybridge    | 2023-05-20T10:33:23.048597  0:00:00.000178 GET     [401] /
```

When accessing the web interface, I get the following response:
`{"error":"The access token is invalid"}`

Am I missing something? I provided the .env file and set the variables according to the comments.

I am wondering what the domain name is not displayed when starting the server "Running on **http://:::8080**", maybe this is the problem?

Thank you so much for providing any hint to get this up and running.

Best,
Felix

**Comment by videah** [comment]
Hello! The docker image `videah/skybridge` was used to debug an issue I was having between architectures, not intended to be used by an end user just yet. I currently don't own an x86 computer so I will need to get Github Actions setup to build images. At the moment please use the Dockerfile included in the repo instead.

As for environment variables, set them on the container itself as the .env file is mostly for development purposes.

If you have any other issues or questions please let me know!

**Comment by felixmueller** [comment]
Hi @videah,

the Docker image seems to work, it just does not serve the website on the root url.

I tried to build the image myself as suggested. I am on arm64. The build fails due to a platform issue:

```
Building skybridge
Sending build context to Docker daemon  3.182MB
Step 1/30 : FROM --platform=linux/arm64 rust:slim-bullseye AS isar-arm64
 ---> 4a0e7d1d467c
Step 2/30 : RUN set -eux;     apt-get update;     apt-get install -y --no-install-recommends --ignore-missing         build-essential libclang-dev wget unzip git
 ---> Using cache
 ---> 594286f078c5
Step 3/30 : WORKDIR /app
 ---> Using cache
 ---> 4dc37150d110
Step 4/30 : RUN wget https://github.com/isar/isar/archive/refs/tags/3.1.0+1.zip
 ---> Using cache
 ---> bfef5192f639
Step 5/30 : RUN unzip 3.1.0+1.zip
 ---> Using cache
 ---> b9bbf8e21f17
Step 6/30 : WORKDIR /app/isar-3.1.0-1
 ---> Using cache
 ---> b4ed5f7a35f9
Step 7/30 : RUN chmod +x tool/build_linux.sh
 ---> Using cache
 ---> c8c28445ff5d
Step 8/30 : RUN tool/build_linux.sh
 ---> Using cache
 ---> 91e2b9f3417f
Step 9/30 : FROM --platform=linux/amd64 bitnami/minideb:bullseye AS isar-amd64
 ---> 225705d9b07f
Step 10/30 : WORKDIR /app/isar-3.1.0-1
 ---> Using cache
 ---> 0e1651e9018d
Step 11/30 : RUN install_packages wget ca-certificates
 ---> [Warning] The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
 ---> Running in 5525d7c60cfc
exec /bin/sh: exec format error
The command '/bin/sh -c install_packages wget ca-certificates' returned a non-zero code: 1
ERROR: Service 'skybridge' failed to build : Build failed
```

Any suggestions?

Thanks!

**Comment by felixmueller** [comment]
Hi again @videah,

is there any possibility to provide pre-build Docker images on Docker Hub for easy install? I just noticed that you pulled the image from Docker Hub 😥

Thank you very much!

**Comment by videah** [comment]
It seems you're using the legacy Docker builder, the way the Dockerfile is setup to handle different architectures requires you to be using BuildKit as your builder.

I am currently working on providing pre-built images as we speak though!
