### ISSUE TITLE
Bridge no longer working in Mona App

### ISSUE THREAD

**Issue by drikkes** [videah/SkyBridge#73]
Hey, on desktop and mobile my Skybridge feed is no longer updating for nearly two days. Tried several stuff like closing, etc. Last one, I removed the account completely – when trying to add it I get this error: "Bad response: unauthorized (401)"

I'm not good at this. Is that a problem on the Skybridge or the Mona side?

**Comment by skjolly** [comment]
Same issue with Ivory for two days. Similar issue when trying to re-add account.

**Comment by lupomancer** [comment]
I was having this issue, seems like generating a new app password fixed it for me

**Comment by drikkes** [comment]
Yes, seems to be working again with a new app password on both mobile and desktop.
