### ISSUE TITLE
Image upload on Ivory fails

### ISSUE THREAD

**Issue by maique** [videah/SkyBridge#8]
Can't get Ivory to post images. Just me?

**Comment by videah** [comment]
Bluesky has a rather strict 1mb file size limit for images and Ivory doesn't respect this limit/compress images so the post will fail, it's possible the image you're trying to post goes over this limit.

I might make it so SkyBridge compresses the image if need be but I'm waiting to see what the long term file size story looks like.

**Comment by maique** [comment]
Oh! No idea the maximum file size was THAT small! I’m certain I haven’t posted a photo so small in ages 🙂 Thank you for the info. Love the bridge, btw. Thanks for that as well. 

: instagram.com/maique
: maiquemadeira.com

**Comment by videah** [comment]
SkyBridge now does the appropriate file size compression as of 44b83d0!

**Comment by MysticalOS** [comment]
Can confirm it works again
https://bsky.app/profile/deadlybossmods.bsky.social/post/3k46ktam4yi25 :D
