### ISSUE TITLE
Jumping Timeline

### ISSUE THREAD

**Issue by ghost** [videah/SkyBridge#83]
Seems like not all posts are loading if a few hours go by. I’ve been doing side by side tests with Bluesky on the web and Ivory. today i gave it 6 hours or so, then did the side by side. Ivory jumped from posts 4 hours old to 1 hour old. Lots of posts missed in between that weren’t on the Ivory timeline but were on Bluesky web.

**Comment by lnlyssg** [comment]
Are you using your own instance or the public one at https://skybridge.fly.dev/? There are API/rate limits and the public-facing one is frequently hitting them as more people are using it, self-hosted also seems to have issues from time to time e.g. https://github.com/videah/SkyBridge/issues/65#issuecomment-2489457696

**Comment by ghost** [comment]
oh rate limit makes sense. i’m just using the public one, i have not one clue how to set up my own instance. thanks for explaining the reason!
