### ISSUE TITLE
hide replies in home timeline

### ISSUE THREAD

**Issue by jvns** [videah/SkyBridge#9]
skybridge is awesome, thanks for making it! I'd love to have a way to hide replies in my home timeline -- right now I'm seeing all the replies that people I follow make, which doesn't match the behaviour of the home timeline on https://bsky.app.

**Comment by videah** [comment]
Thank you so much, glad you like it! I'll absolutely add this as an option, I'm thinking of exposing it as an environment variable if that sounds suitable?

**Comment by felixmueller** [comment]
I would also vote for adding SHOW_REPLIES as a variable and hide them by default as it is a bit confusing in its current state.

**Comment by videah** [comment]
I tend to see a lot of replies on my feed made towards people I don't follow so I'm not sure if that is the default behaviour of bsky.app? But considering issue #12 it might be worth enabling by default anyway to avoid confusion for new users

**Comment by cbirdsong** [comment]
Is Skybridge able to see/respond to the value of these settings? 

![Screenshot: A toggle switch and range slider with the following label/description: "Show Replies: Adjust the number of likes a reply must have to be shown in your feed."](https://github.com/videah/SkyBridge/assets/1672206/e8a300d0-5f9c-45b5-b6d3-e1a377888b90)

(also: just set this up, it's very neat, thank you for making it!)

**Comment by videah** [comment]
> Is Skybridge able to see/respond to the value of these settings?

These settings are only stored locally as far as I can tell unfortunately 🥲

**Comment by mergesort** [comment]
I [asked Emily earlier](https://bsky.app/profile/emily.bsky.team/post/3jyrw7jet232j) and she confirmed that those settings aren't available more widely unfortunately.

**Comment by felixmueller** [comment]
Now that the traffic on Bluesky is slowly increasing: I would really like to have a way to turn off the Replies from the Home Timeline.
I would be very happy about this in a small feature update!
Thanks @videah !

**Comment by MikeASchneider** [comment]
Hi, I'm also really enjoying using SkyBridge with Ivory!

Perhaps an ideal solution here would be to allow users to log into SkyBridge directly via the web to change the Home Feed Preferences that are stored locally in the bsky app, however this is obviously a _much_ larger task and probably not worth the effort for now.

The default behavior of bluesky is showing replies with >2 likes, which is frankly a ridiculous decision that everybody seems to hate and I think there's no need for SkyBridge to respect it. I think just acting as if the switch is set to "No" would be a totally reasonable default, especially considering that right now replies don't even display correctly in Ivory (#12) so it makes your feed very difficult to understand.

**Comment by felixmueller** [comment]
@videah, @MikeASchneider,

I get that it's a bit tricky to control the behavior on a per-user basis.

As a start, I would really like to be able to disable replies in my self hosted instance globally by introducing a global config variable to disable or enable replies in the home timeline for all users.

Thank you very much!

**Comment by videah** [comment]
As of 7dea18b we can store per-user preferences alongside the auth token, you can now choose to show or not show replies when signing in. I haven't tested it too much so let me know if you encounter any issues!

<img width="1136" alt="image" src="https://github.com/videah/SkyBridge/assets/4761786/3356cc96-de57-4289-ab14-00f4e4ebc064">

**Comment by felixmueller** [comment]
Awesome! Thank you so much!

**Comment by xnuk** [comment]
This seems to hide self-replies (aka thread), which I don't want to hide
